FROM nvidia/cuda:12.8.1-devel-ubuntu24.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        cmake \
        ninja-build \
        pkg-config \
        build-essential \
        git \
        python3 \
        libavcodec-dev \
        libavformat-dev \
        libavutil-dev \
        libswscale-dev \
        libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*
